models/Topic.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use yii\caching\DbDependency;

class Topic extends ActiveRecord
{
    const SCENARIO_ADD = 1;
    const SCENARIO_NEW = 2;
    const SCENARIO_AUTHOR_EDIT = 3;
    const SCENARIO_ADMIN_EDIT = 10;
    const SCENARIO_ADMIN_CHGNODE = 11;

    public static function tableName()
    {
        return '{{%topic}}';
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_ADD] = ['title'];
        $scenarios[self::SCENARIO_NEW] = ['title', 'node_id'];
        $scenarios[self::SCENARIO_AUTHOR_EDIT] = ['title'];
        $scenarios[self::SCENARIO_ADMIN_EDIT] = ['invisible', 'comment_closed', 'title'];
        $scenarios[self::SCENARIO_ADMIN_CHGNODE] = ['node_id'];
        return $scenarios;
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at', 'replied_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'node_id'], 'required'],
            ['invisible', 'boolean'],
            ['comment_closed', 'boolean'],
            ['node_id', 'integer'],
            ['node_id', 'exist', 'targetClass' => '\app\models\Node', 'targetAttribute' => 'id', 'message' => '节点不存在'],
			[['title'], 'trim'],
            [['title'], 'string', 'length' => [4, 120]],
//            [['content'], 'string', 'max' => 20000],
//            ['content', 'filter', 'filter' => 'nl2br'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'node_id' => '所属节点',
            'invisible' => '隐藏主题',
            'comment_closed' => '关闭评论',
            'title' => '标题',
        ];
    }

	public function getNode()
    {
        return $this->hasOne(Node::className(), ['id' => 'node_id'])
			->select(['id', 'ename', 'name']);
    }

	public function getTopic()
    {
        return $this->hasOne(self::className(), ['id' => 'id'])
			->select(['id', 'node_id', 'user_id', 'reply_id', 'replied_at', 'comment_count', 'title']);
    }

	public function getContent()
    {
        return $this->hasOne(TopicContent::className(), ['topic_id' => 'id'])
			->select(['topic_id', 'content']);
    }

	public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id'])
			->select(['id', 'username', 'status', 'avatar']);
    }

	public function getLastReply()
    {
        return $this->hasOne(User::className(), ['id' => 'reply_id'])
			->select(['id', 'username']);
    }

	public function getComments()
    {
        return $this->hasMany(Comment::className(), ['topic_id' => 'id']);
    }

	public function getFavorites()
    {
        return $this->hasMany(Favorite::className(), ['target_id' => 'id'])->onCondition([Favorite::tableName().'.type'=>Favorite::TYPE_TOPIC]);
    }

	public function getAuthorFollowedBy()
    {
        return $this->hasMany(Favorite::className(), ['target_id' => 'user_id']);
    }

	public static function getRedirectUrl($tid, $position=0, $ip=1, $np=1)
    {
		$url = ['topic/view', 'id' => $tid];

		if($position > 0) {
			$url['#'] = 'reply'.$position;
			$all = Comment::find()->where(['topic_id'=>$tid])->andWhere(['<=', 'position', $position])->count('id');
			$page = ceil($all / Yii::$app->params['settings']['comment_pagesize']);
			if($page > 1) {
				$url['p'] = $page;
			}
		}
		if($ip > 1) {
			$url['ip'] = $ip;
		}
		if($np > 1) {
			$url['np'] = $np;
		}
		return $url;
    }

	public function afterSave($insert, $changedAttributes)
	{
		if ($insert === true) {
			(new History([
				'user_id' => $this->user_id,
				'action' => History::ACTION_ADD_TOPIC,
				'action_time' => $this->created_at,
				'target' => $this->id,
			]))->save(false);
			Siteinfo::updateCounterInfo('addTopic');
			UserInfo::updateCounterInfo('addTopic', $this->user_id);
			Node::updateCounterInfo('addTopic', $this->node_id);
			Notice::afterTopicInsert($this);
		}
		return parent::afterSave($insert, $changedAttributes);
	}

	public function afterDelete()
	{
		(new History([
			'user_id' => $this->user_id,
			'action' => History::ACTION_DELETE_TOPIC,
			'target' => $this->id,
		]))->save(false);
		TopicContent::deleteAll(['topic_id'=> $this->id]);
		Node::updateCounterInfo('deleteTopic', $this->node_id);
		UserInfo::updateCounterInfo('deleteTopic', $this->user_id);
		$count = Comment::afterTopicDelete($this->id);
		Siteinfo::updateCountersInfo( ['topics'=>-1, 'comments'=>-$count] );
		Favorite::afterTopicDelete($this->id);
		Notice::afterTopicDelete($this->id);
		return parent::afterDelete();
	}

	public static function afterCommentInsert($id, $reply_id)
	{
		return static::updateAll([
			'updated_at'=>time(),
			'replied_at'=>time(),
			'reply_id' => $reply_id,
			'comment_count'=> (new Expression('`comment_count` + 1')),
		], ['id'=> $id]);
	}

	public static function afterCommentDelete($id)
	{
		return static::updateAll([
			'updated_at'=>time(),
			'comment_count'=> (new Expression('`comment_count` - 1')),
		], ['id'=> $id]);
	}


/*
	public static function afterView($id, $increase=1)
	{
		return static::findOne($id)->updateCounters(['views' => $increase]);
	}
*/

	public static function updateCounterInfo($action, $id)
	{
		$upd = [
			'followTopic' => ['favorite_count'=>1],
			'unfollowTopic' => ['favorite_count'=>-1],
		];

		if( !isset($upd[$action]) ) {
			return false;
		}
		return static::updateAllCounters($upd[$action], ['id'=>$id]);
	}

	public static function getHotTopics()
	{
		$key = 'hot-topics';
		$cache = Yii::$app->getCache();
		$settings = Yii::$app->params['settings'];

		if ( intval($settings['cache_enabled']) === 0 || ($models = $cache->get($key)) === false ) {
		    $models = static::find()->select(['id', 'title'])
				->where(['>','created_at', time()-24*60*60])
				->orderBy(['comment_count'=>SORT_DESC, 'replied_at'=>SORT_DESC])
//				->with(['author'])
		        ->limit($settings['hot_topic_num'])
				->asArray()
		        ->all();
			if ( intval($settings['cache_enabled']) !== 0 ) {
				if ($models === null) {
					$models = [];
				}
				$cache->set($key, $models, intval($settings['cache_time'])*60);
			}
		}
		return $models;
	}

	public static function getTopicFromView($id)
	{
		$key = 'topic-'.$id;
		$cache = Yii::$app->getCache();
		$settings = Yii::$app->params['settings'];

		if ( intval($settings['cache_enabled']) === 0 || ($model = $cache->get($key)) === false) {
			$model = static::find()->where(['id'=>$id])->with(['content', 'node', 'author'])->one();
	        if ( !$model ) {
	            throw new \yii\web\NotFoundHttpException('未找到id为['.$id.']的主题');
	        }
		}

		$model->updateCounters(['views' => 1]);
		if ( intval($settings['cache_enabled']) !== 0 ) {
			$dep = new DbDependency(['sql'=>'SELECT updated_at FROM '. self::tableName(). 'where id='.$id]);
			$cache->set($key, $model, intval($settings['cache_time'])*60, $dep);
		}
		return $model;
	}

	public static function getTopicsFromNode($node_id, $pages)
	{
		$key = 'topics-n-'. $node_id. '-p-'. $pages->getPage();
		$cache = Yii::$app->getCache();
		$settings = Yii::$app->params['settings'];

		if ( intval($settings['cache_enabled']) === 0 || ($models = $cache->get($key)) === false) {
		    $models = static::find()->where(['node_id' => $node_id])
				->select('id')
				->orderBy(['replied_at'=>SORT_DESC])
				->offset($pages->offset)
				->with(['topic.author', 'topic.lastReply'])
		        ->limit($pages->limit)
				->asArray()
		        ->all();

			if ( intval($settings['cache_enabled']) !== 0 ) {
				if ($models === null) {
					$models = [];
				}
				$dep = new DbDependency(['sql'=>'SELECT MAX(updated_at) FROM '. self::tableName(). 'where node_id='.$node_id]);
				$cache->set($key, $models, intval($settings['cache_time'])*60, $dep);
			}
		}
		return $models;
	}

	public static function getTopicsFromIndex($pages)
	{
		$key = 'topics-index-p-'. $pages->getPage();
		$cache = Yii::$app->getCache();
		$settings = Yii::$app->params['settings'];

		if ( intval($settings['cache_enabled']) === 0 || ($models = $cache->get($key)) === false) {
		    $models = static::find()->select('id')->orderBy(['replied_at'=>SORT_DESC])->offset($pages->offset)
				->with(['topic.node', 'topic.author', 'topic.lastReply'])
		        ->limit($pages->limit)
				->asArray()
		        ->all();
			if ( intval($settings['cache_enabled']) !== 0 ) {
				$dep = new DbDependency(['sql'=>'SELECT MAX(updated_at) FROM '.Topic::tableName()]);
				$cache->set($key, $models, intval($settings['cache_time'])*60, $dep);
			}
		}
		return $models;
	}

}

controllers/TopicController.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use yii\caching\DbDependency;
use app\models\User;
use app\models\Topic;
use app\models\TopicContent;
use app\models\Comment;
use app\models\Node;
use app\models\History;
use app\lib\Util;

class TopicController extends AppController
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['new', 'add', 'edit'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['new', 'add', 'edit'],
                        'matchCallback' => function ($rule, $action) {
							$me = Yii::$app->getUser();
                            return ( !$me->getIsGuest() && ($me->getIdentity()->isActive() || $me->getIdentity()->isAdmin()) );
                        },
                    ],
                ],
				'denyCallback' => function ($rule, $action) {
					$me = Yii::$app->getUser();
					if( !$me->getIsGuest() && $me->getIdentity()->isInactive() ) {
					    throw new ForbiddenHttpException('您的会员帐号还没有激活，请先激活');
					} else {
					    throw new ForbiddenHttpException('您没有执行此操作的权限。');
					}
				},
            ],
        ];
    }

    public function actionIndex()
    {
	    $pages = new Pagination([
			'totalCount' => Topic::find()->count('id'),
			'pageSize' => intval($this->settings['index_pagesize']),
			'pageParam' => 'p',
		]);
	    return $this->render('index', [
	         'topics' => Topic::getTopicsFromIndex($pages),
	         'pages' => $pages,
	    ]);
    }

	public function actionNode($name)
	{
		$node = $this->findNodeModel($name);
	    $pages = new Pagination([
			'totalCount' => $node['topic_count'],
			'pageSize' => intval($this->settings['list_pagesize']),
			'pageParam' => 'p',
		]);

	    return $this->render('node', [
			 'node' => $node,
	         'topics' => Topic::getTopicsFromNode($node['id'], $pages),
	         'pages' => $pages,
	    ]);
	}

    public function actionView($id)
    {
		$topic = Topic::getTopicFromView($id);
		$pages = new Pagination([
			'totalCount' => $topic->comment_count,
			'pageSize' => intval($this->settings['comment_pagesize']),
			'pageParam' => 'p',
		]);

        return $this->render('view', [
            'topic' => Util::convertModelToArray($topic),
			'comments' => Comment::getCommentsFromView($id, $pages),
	        'pages' => $pages,
       ]);
    }
/*
    public function actionClick($id)
	{
		print_r(Topic::afterView($id));die;
		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
	    return [
	        'views' => Topic::afterView($id),
	    ];
	}
*/
    public function actionAdd($node)
    {
		$request = Yii::$app->getRequest();
		$node = $this->findNodeModel($node);

        $topic = new Topic(['node_id' => $node['id'], 'user_id' => Yii::$app->getUser()->id]);
        $content = new TopicContent();
        if ( $topic->load($request->post()) && $topic->validate() && 
			$content->load($request->post()) && $content->validate() && 
			$topic->save(false) ) {
			$content->topic_id = $topic->id;
			$content->save(false);
            return $this->redirect(['view', 'id' => $topic->id]);
        } else {
            return $this->render('add', [
                'model' => $topic,
                'content' => $content,
                'node' => $node,
            ]);
        }
    }

    public function actionNew()
    {
		$request = Yii::$app->getRequest();

        $topic = new Topic(['scenario' => Topic::SCENARIO_NEW, 'user_id' => Yii::$app->getUser()->id]);
        $content = new TopicContent();

        if ( $topic->load($request->post()) && $topic->validate() && 
			$content->load($request->post()) && $content->validate() && 
			$topic->save(false) ) {
			$content->topic_id = $topic->id;
			$content->save(false);
            return $this->redirect(['view', 'id' => $topic->id]);
        }
        return $this->render('new', [
            'model' => $topic,
            'content' => $content,
        ]);
    }

    public function actionEdit($id)
    {
		$request = Yii::$app->getRequest();
		$me = Yii::$app->getUser()->getIdentity();

        $model = $this->findTopicModel($id, ['content','node']);
		if( !$me->canEdit($model) ) {
			throw new ForbiddenHttpException('您没有权限修改或已超过可修改时间。');
		}
		if( $me->isAdmin() ) {
			$model->scenario = Topic::SCENARIO_ADMIN_EDIT;
		} else {
			$model->scenario = Topic::SCENARIO_AUTHOR_EDIT;
		}
		if( !($content = $model->content) ) {
			$content = new TopicContent(['topic_id'=>$model->id]);
		}
        if ($model->load($request->post()) && $model->validate() && 
			$content->load($request->post()) && $content->validate() && 
			$model->save(false) && $content->save(false)) {
			(new History([
				'user_id' => $me->id,
				'action' => History::ACTION_EDIT_TOPIC,
				'action_time' => $model->updated_at,
				'target' => $model->id,
			]))->save(false);

           return $this->redirect(Topic::getRedirectUrl($id, 0, $request->get('ip', 1), $request->get('np', 1)));
        }
        return $this->render('edit', [
            'model' => $model,
            'content' => $content,
        ]);
    }

    protected function findTopicModel($id, $with=null)
    {
		$model = Topic::find()->where(['id'=>$id]);
		if ( !empty($with) ) {
			$model = $model->with($with);
		}
		$model = $model->one();
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('未找到id为['.$id.']的主题');
        }
    }

    protected function findNodeModel($name, $with=null)
    {
		$model = Node::find()->select(['id', 'name', 'ename', 'topic_count', 'about'])->where(['ename' => $name]);
		if ( !empty($with) ) {
			$model = $model->with($with);
		}
		$model = $model->asArray()->one();
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('未找到['.$name.']的节点');
        }
    }

    protected function newPagination($totalCount)
    {
		return new Pagination(['totalCount' => $totalCount, 'pageSize' => intval($this->settings['comment_pagesize']), 'pageParam'=>'p']);
    }

}

views/topic/add.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;

$settings = Yii::$app->params['settings'];
$this->title = '创建新主题';
?>

<div class="row">
<div class="col-md-8 sf-left">

<div class="box">
	<div class="inner">
		<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', 
			Html::a(Html::encode($node['name']), ['topic/node', 'name'=>$node['ename']]), 
			'&nbsp;/&nbsp;', $this->title ?>
	</div>
	<div class="cell">
    <?= $this->render('_form', [
        'model' => $model,
        'content' => $content,
		'action' => 'add',
    ]) ?>
	</div>
</div>

</div>

<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>

</div>

views/topic/index.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\Node;

$settings = Yii::$app->params['settings'];
$currentPage = $pages->page+1;
$this->title = Html::encode($settings['site_name']).'首页';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 col-sm-12 sf-left">

<div class="box">
	<div class="inner">
	<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;最近更新' ?>
	</div>
	<?php
	foreach($topics as $topic){
		$topic = $topic['topic'];
		$url = ['topic/view', 'id'=>$topic['id']];
//		if ( $currentPage > 1) {
			$url['ip'] = $currentPage;
//		}
		echo '<div class="cell item clearfix">
				<div class="item-avatar">',
					Html::a(Html::img('@web/'.str_replace('{size}', 'normal', $topic['author']['avatar']), ["alt" => Html::encode($topic['author']['username'])]), ['user/view', 'username'=>Html::encode($topic['author']['username'])]),
				'</div>
			 	 <div class="item-content">
					<div class="item-title">',
					Html::a(Html::encode($topic['title']), $url),
					'</div>
					<div class="small gray">';
		if($topic['comment_count'] > 0){
		    $gotopage = ceil($topic['comment_count']/intval($settings['comment_pagesize']));
		    if($gotopage > 1){
				$url['p'] = $gotopage;
		    }
			echo '<div class="item-commentcount">', Html::a($topic['comment_count'], $url, ['class'=>'count_livid']),'</div>';
		}
					echo Html::a(Html::encode($topic['node']['name']), ['topic/node', 'name'=>$topic['node']['ename']], ['class'=>'node']),
					'  •  <strong>', Html::a(Html::encode($topic['author']['username']),['user/view', 'username'=>Html::encode($topic['author']['username'])]), '</strong>',
					' •  ', Yii::$app->formatter->asRelativeTime($topic['replied_at']);
		if ($topic['comment_count']>0) {
					echo '<span class="item-lastreply"> •  最后回复者 ', Html::a(Html::encode($topic['lastReply']['username']), ['user/view', 'username'=>Html::encode($topic['lastReply']['username'])]), '</span>';
		}
					echo '</div>
				</div>';


		echo '</div>';
	}
	?>
	<div class="item-pagination">
	<?php
	echo LinkPager::widget([
	    'pagination' => $pages,
		'maxButtonCount'=>5,
	]);
	?>
	</div>

</div>

<?php
if ( intval($settings['cache_enabled'])===0 || $this->beginCache('f-hot-nodes', ['duration' => intval($settings['cache_time'])*60])) :
?>
<div class="box">
	<div class="inner gray"><span class="fr"><?=Html::a('浏览全部节点', ['node/index']) ?></span>热门节点
	</div>
	<div class="cell hot-nodes sf-btn">
<?php
	$hotNodes = Node::getHotNodes();
	foreach($hotNodes as $hn) {
		echo Html::a(Html::encode($hn['name']), ['topic/node', 'name'=>$hn['ename']], ['class'=>'btn btn-default']);
	}
?>
	</div>
</div>
<?php
if ( intval($settings['cache_enabled']) !== 0 ) {
	$this->endCache();
}
endif;
?>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_index-right') ?>
</div>
<!-- sf-right end -->

</div>

views/topic/new.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Node;

$settings = Yii::$app->params['settings'];

$this->registerAssetBundle('app\assets\Select2Asset');
$this->registerJs('$(".nodes-select2").select2({placeholder:"请选择一个节点",allowClear: true});');

$editor = new \app\lib\Editor(['editor'=>$settings['editor']]);
$editor->registerAsset($this);

$this->title = '创建新主题';
?>

<div class="row">
<div class="col-md-8 sf-left">

<div class="box">
	<div class="inner">
		<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
	</div>
	<div class="cell">
<?php $form = ActiveForm::begin(); ?>
		<p>主题标题 <span class="gray">( 如果标题能够表达完整内容，主题内容可为空 )</span></p>
	    <?= $form->field($model, 'title')->textArea(['rows' => '4', 'maxlength'=>120])->label(false) ?>
		<p>主题内容</p>
		<?= $form->field($content, 'content')->textArea(['id'=>'editor', 'maxlength'=>30000])->label(false) ?>
	    <?= $form->field($model, 'node_id')->dropDownList(array(''=>'')+Node::getNodeList(), ['class'=>'form-control nodes-select2'])->label(false) ?>
		<div class="new-hot-nodes">热门节点：
		<?php
			$hotNodes = Node::getHotNodes();
			foreach($hotNodes as $hn) {
				echo Html::a(Html::encode($hn['name']), 'javascript:chooseNode("'.$hn['id'].'");', ['class'=>'node']);
			}
		?>
		</div>
		<div class="form-group">
			<?= Html::submitButton('创建', ['class' => 'btn btn-primary']) ?>
		</div>
<?php ActiveForm::end(); ?>
	</div>
</div>

</div>

<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>

</div>

views/topic/node.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\Topic;
use app\models\User;
use app\models\Favorite;

$settings = Yii::$app->params['settings'];
$currentPage = $pages->page+1;
if (!Yii::$app->getUser()->getIsGuest() && Yii::$app->getUser()->getIdentity()->isActive()) {
	$follow = Favorite::checkFollow(Yii::$app->getUser()->id, Favorite::TYPE_NODE, $node['id'])?Html::a('取消收藏', ['favorite/cancel', 'type'=>'node', 'id'=>$node['id']], [
	    'data' => [
	        'method' => 'post',
	    ]]):Html::a('加入收藏', ['favorite/add', 'type'=>'node', 'id'=>$node['id']]);
	$follow = '  •  '.$follow;
} else {
	$follow = '';
}

$this->title = Html::encode($node['name']);
?>

<div class="row">

<!-- sf-left start -->
<div class="col-md-8 sf-left">

<div class="box">
	<div class="inner">
		<span class="fr gray small">主题总数 <?=$node['topic_count'] ?><?= $follow ?></span>
		<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		<p class="gray"><?= (new \parsedown\Parsedown())->text(Html::encode($node['about'])) ?></p>
		<?php
			if (!Yii::$app->getUser()->getIsGuest() && Yii::$app->getUser()->getIdentity()->status >= User::STATUS_ACTIVE ) {
				echo Html::a('创建主题', ['topic/add', 'node'=>$node['ename']], ['class'=>'btn btn-primary']);
			}
		?>
	</div>
	<?php
	foreach($topics as $topic){
		$topic = $topic['topic'];
		$url = ['topic/view', 'id'=>$topic['id']];
//		if ( $currentPage > 1) {
			$url['np'] = $currentPage;
//		}
		echo '<div class="cell item clearfix">
				<div class="item-avatar">',
					Html::a(Html::img('@web/'.str_replace('{size}', 'normal', $topic['author']['avatar']), ["alt" => Html::encode($topic['author']['username'])]), ['user/view', 'username'=>Html::encode($topic['author']['username'])]),
				'</div>
			 	 <div class="item-content">
					<div class="item-title">',
					Html::a(Html::encode($topic['title']), $url),
					'</div>
					<div class="small">';
		if($topic['comment_count'] > 0){
		    $gotopage = ceil($topic['comment_count']/$settings['comment_pagesize']);
		    if($gotopage > 1){
				$url['p'] = $gotopage;
		    }
			echo '<div class="item-commentcount">', Html::a($topic['comment_count'], $url, ['class'=>'count_livid']),'</div>';
		}
					echo '<strong>', Html::a(Html::encode($topic['author']['username']),['user/view', 'username'=>Html::encode($topic['author']['username'])]), '</strong>',
					' •  ', Yii::$app->formatter->asRelativeTime($topic['replied_at']);
		if ($topic['comment_count']>0) {
					echo '<span class="item-lastreply"> •  最后回复来自 ', Html::a(Html::encode($topic['lastReply']['username']), ['user/view', 'username'=>Html::encode($topic['lastReply']['username'])]), '</span>';
		}
					echo '</div>
				</div>';
		echo '</div>';
	}
	?>
	<div class="item-pagination">
	<?php
	echo LinkPager::widget([
	    'pagination' => $pages,
		'maxButtonCount'=>5,
	]);
	?>
	</div>

</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>