models/User.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use app\lib\Util;

class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_BANNED = 0;
    const STATUS_INACTIVE = 8;
    const STATUS_ADMIN_VERIFY = 9;
    const STATUS_ACTIVE = 10;
    const ROLE_MEMBER = 0;
    const ROLE_ADMIN = 10;
	const USERNAME_PATTERN = '/^[a-zA-Z0-9\x{4e00}-\x{9fa5}]*$/u';
	const USER_MENTION_PATTERN = '/\B\@([a-zA-Z0-9\x{4e00}-\x{9fa5}]{4,20})/u';

	public static $statusOptions = [
		0 => '被屏蔽用户',
		8 => '待激活用户',
		9 => '待管理员验证用户',
		10 => '正常用户',
	];

	public static $roleOptions = [
		0 => '用户组',
		10 => '管理员',
	];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['avatar', 'safe'],
//            ['role', 'default', 'value' => self::ROLE_MEMBER],
//            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'integer', 'max'=>self::STATUS_ACTIVE, 'min'=>self::STATUS_BANNED],
        ];
    }

	public function getNoticeCount()
    {
        return Notice::find()->where(['status'=>0, 'target_id' => $this->id])->count('id');
    }

	public function getNotices()
    {
        return $this->hasMany(Notice::className(), ['target_id' => 'id'])
			->where(['status'=>0])->orderBy(['updated_at'=>SORT_DESC]);
    }

	public function getTopics()
    {
        return $this->hasMany(Topic::className(), ['user_id' => 'id'])
			->select(['id', 'node_id', 'user_id', 'reply_id', 'title', 'comment_count', 'replied_at'])
			->limit(10)->orderBy(['id'=>SORT_DESC]);
    }

	public function getComments()
    {
        return $this->hasMany(Comment::className(), ['user_id' => 'id'])
			->select(['id', 'user_id', 'topic_id', 'created_at', 'invisible', 'content'])
			->limit(10)->orderBy(['id'=>SORT_DESC]);
    }

	public function getUserInfo()
    {
        return $this->hasOne(UserInfo::className(), ['user_id' => 'id']);
    }

	public function isAdmin()
	{
		return (intval($this->role) === self::ROLE_ADMIN);
	}

	public function isActive()
	{
		return (intval($this->status) >= self::STATUS_ACTIVE);
	}

	public function isInactive()
	{
		return (intval($this->status) === self::STATUS_INACTIVE || intval($this->status) === self::STATUS_ADMIN_VERIFY);
	}

	public function isWatingActivation()
	{
		return (intval($this->status) === self::STATUS_INACTIVE);
	}

	public function isWatingVerification()
	{
		return (intval($this->status) === self::STATUS_ADMIN_VERIFY);
	}

	public function isAuthor($user_id)
	{
		return ($this->id == $user_id);
	}

	public function isExpired($created_at)
	{
		return ( time() > $created_at + intval(Yii::$app->params['settings']['edit_space'])*60 );
	}

	public function canEdit($model, $status=0)
	{
		return ( self::isAdmin() || $status == 0 && self::isActive()
				 && self::isAuthor($model['user_id'])
				 && !self::isExpired($model['created_at'])
				);
	}

	public function canAdd($model)
	{
		return ( self::isAdmin() || self::isActive() && !self::isExpired($model['created_at']) );
	}

	public function canReply($model)
	{
		return ( intval($model['comment_closed']) === 0 && self::isActive() );
	}

	public function getStatus()
	{
		return self::$statusOptions[$this->status];
	}

	public function getRole()
	{
		return self::$roleOptions[$this->role];
	}

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
//        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
        return static::find()->where(['id' => $id])
				->andWhere(['>=', 'status', self::STATUS_INACTIVE])
				->one();
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
//        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
        return static::find()->where(['username' => $username])
				->andWhere(['>=', 'status', self::STATUS_INACTIVE])
				->one();
    }

    public static function findByEmail($email)
    {
        return static::find()->where(['email' => $email])
				->andWhere(['>=', 'status', self::STATUS_INACTIVE])
				->one();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Util::generateRandomString();
    }

	public function afterSave($insert, $changedAttributes)
	{
		if ($insert === true) {
			$userIP = sprintf("%u", ip2long(Yii::$app->getRequest()->getUserIP()));
			(new UserInfo([
				'user_id' => $this->id,
				'reg_ip' => $userIP,
			]))->save(false);
			Siteinfo::updateCounterInfo('addUser');
/*			if ( intval(Yii::$app->params['settings']['email_verify']) === 1) {
				Token::sendActivateMail($this);
			}*/
			(new History([
				'user_id' => $this->id,
				'action' => History::ACTION_REG,
				'action_time' => $this->created_at,
				'target' => $userIP,
			]))->save(false);
		}
		return parent::afterSave($insert, $changedAttributes);
	}
/*
	public function afterDelete()
	{
		$userId = Yii::$app->getUser()->id;
		(new History([
			'user_id' => $userId,
			'action' => History::ACTION_DELETE_USER,
			'target' => $this->id,
		]))->save(false);
		$userInfo = $this->userInfo;
		$userInfo->delete();
		Topic::afterUserDelete($this->id);
		Comment::afterUserDelete($this->id);
		Siteinfo::updateCountersInfo( ['users'=>-1, 'topics'=>$userInfo->topic_count, 'comments'=>$userInfo->comment_count] );
		return parent::afterDelete();
	}
*/
}

controllers/UserController.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use yii\imagine\Image;
use yii\web\UploadedFile;
use app\models\User;
use app\models\UserInfo;
use app\models\Notice;
use app\models\Topic;
use app\models\Comment;
use app\models\Token;
use app\models\UploadForm;
use app\models\ChangePasswordForm;
use app\models\ChangeEmailForm;
use app\lib\Util;

class UserController extends AppController
{
	private $resizes = [
		'large'=>'73x73',
		'normal'=>'48x48',
		'small'=>'24x24',
	];

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'avatar' => ['post'],
                    'edit-profile' => ['post'],
                    'change-email' => ['post'],
                    'change-email' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['setting', 'avatar', 'notifications', 'edit-profile', 'change-password', 'change-email', 'send-activate-mail'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['setting', 'avatar', 'notifications', 'edit-profile', 'change-password', 'change-email', 'send-activate-mail'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionNotifications()
    {
		$myId = Yii::$app->getUser()->id;
		Notice::updateAll([
			'updated_at'=>time(),
			'status'=> 1,
		], ['status'=> 0, 'target_id'=>$myId]);

		$query = Notice::find()->where(['target_id'=>$myId]);
	    $countQuery = clone $query;
	    $pages = new Pagination(['totalCount' => $countQuery->count('id')]);
	    $notices = $query->orderBy(['id'=>SORT_DESC])->offset($pages->offset)
			->with(['source', 'topic'])
	        ->limit($pages->limit)
			->asArray()
	        ->all();
	    return $this->render('notifications', [
	         'notices' => $notices,
	         'pages' => $pages,
	    ]);
    }

    public function actionView($username)
    {
		$model = $this->findUserModel($username, ['userInfo', 'topics.node', 'topics.lastReply', 'comments.topic.author']);
	    return $this->render('view', [
	         'user' => $model,
	    ]);
    }

    public function actionTopics($username)
    {
		$user = $this->findUserModel($username, ['userInfo']);
	    $pages = new Pagination(['totalCount' => $user['userInfo']['topic_count'], 'pageSize' => $this->settings['list_pagesize'], 'pageParam'=>'p']);
	    $topics = Topic::find()->select('id')->where(['user_id' => $user['id']])
			->orderBy(['id'=>SORT_DESC])->offset($pages->offset)
			->with(['topic.node', 'topic.lastReply'])
	        ->limit($pages->limit)
			->asArray()
	        ->all();

	    return $this->render('topics', [
			 'user' => $user,
	         'topics' => $topics,
	         'pages' => $pages,
	    ]);
    }

    public function actionComments($username)
    {
		$user = $this->findUserModel($username, ['userInfo']);
	    $pages = new Pagination(['totalCount' => $user['userInfo']['comment_count'], 'pageSize' => $this->settings['list_pagesize'], 'pageParam'=>'p']);
	    $comments = Comment::find()->select(['id', 'created_at', 'topic_id', 'content'])->where(['user_id' => $user['id']])
			->orderBy(['id'=>SORT_DESC])->offset($pages->offset)
			->with(['topic.author'])
	        ->limit($pages->limit)
			->asArray()
	        ->all();

	    return $this->render('comments', [
			 'user' => $user,
	         'comments' => $comments,
	         'pages' => $pages,
	    ]);
    }

	public function actionSetting()
	{
        return $this->render('setting');
	}

    public function actionEditProfile()
    {
		$me = Yii::$app->getUser()->getIdentity();
		$userInfo = $me->userInfo;
		$userInfo->scenario = UserInfo::SCENARIO_EDIT;

		if ( $userInfo->load(Yii::$app->getRequest()->post()) && $userInfo->save() ) {
			Yii::$app->getSession()->setFlash('EditProfileOK', '您的会员信息修改成功。');
		} else {
			Yii::$app->getSession()->setFlash('EditProfileNG', implode('<br />', $userInfo->getFirstErrors()));
		}

        return $this->redirect(['user/setting', '#'=>'info']);
    }

    public function actionChangeEmail()
    {
        $model = new ChangeEmailForm();
		$model->load(Yii::$app->getRequest()->post());
		$result = $model->apply();
		Yii::$app->getSession()->setFlash($result[0], $result[1]);

//		return $this->goBack();
        return $this->redirect(['user/setting', '#'=>'email']);
    }

    public function actionChangePassword()
    {
        $model = new ChangePasswordForm();
		$model->load(Yii::$app->getRequest()->post());
		$result = $model->apply();
		Yii::$app->getSession()->setFlash($result[0], $result[1]);

//		return $this->goBack();
        return $this->redirect(['user/setting', '#'=>'password']);
    }

    public function actionSendActivateMail()
    {
		if (Token::sendActivateMail(Yii::$app->getUser()->getIdentity())) {
			Yii::$app->getSession()->setFlash('activateMailOK', '邮件发送成功，请进邮箱点击激活链接');
		} else {
			Yii::$app->getSession()->setFlash('activateMailNG', '邮件发送失败');
		}

//		return $this->goBack();
        return $this->redirect(['user/setting']);
    }

    public function actionAvatar()
    {
		$session = Yii::$app->getSession();
        $model = new UploadForm();
		$suffix = 'png';

		$me = Yii::$app->getUser()->getIdentity();

        $model->file = UploadedFile::getInstance($model, 'file');

        if ($model->file && $model->validate()) {
	        $name = $me->id;
			$myId = strtolower(Util::shorturl($me->id));
			$savePath = 'avatar/'.substr($myId,0,1).'/'.substr($myId,1,1);
			$avatar = $savePath. '/'.$name . '_{size}.' . $suffix . '?m='.time();
			$this->resizeAvator( $this->resizes, $model->file->tempName, $savePath, $name, $suffix);
			$me->avatar = $avatar;
			$me->save(false);
            $session->setFlash('setAvatarOK', '头像设定成功，显示可能有延迟，请刷新。');
        } else {
            $session->setFlash('setAvatarNG', '头像设定失败');
		}

        return $this->redirect(['user/setting', '#'=>'avatar']);
    }

	private function resizeAvator($resizes, $srcFile, $savePath, $name, $suffix='png')
	{
		@mkdir($savePath, 0755, true);
		foreach($resizes as $key=>$resize) {
			list($width, $height) = explode('x', $resize);
			Image::thumbnail($srcFile, $width, $height)->save($savePath. '/' . $name . '_' . $key . '.' . $suffix);
		}
		return true;
	}

/*
    private function saveTemporaryImage($filename, $name, $size)
    {
        list($width, $height) = explode('x', $size);

        $file = Image::getImagine()->open($filename);

        if ($file->getSize()->getWidth() < $width) {
            $file->resize($file->getSize()->widen($width));
        }

        if ($file->getSize()->getHeight() < $height) {
            $file->resize($file->getSize()->heighten($height));
        }

        $file->thumbnail(new \Imagine\Image\Box::Box($width, $height), \Imagine\Image\ManipulatorInterface::THUMBNAIL_OUTBOUND)
            ->save('avatar/' . $name);

        return $name;
    }
*/

    protected function findUserModel($username, $with=null)
    {
		$model = User::find()->select(['id', 'created_at', 'status', 'username', 'avatar'])->where(['username'=>$username]);
		if ( !empty($with) ) {
			$model = $model->with($with);
		}
		$model = $model->asArray()->one();

        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('未找到['.$username.']的用户');
        }
    }

}

views/user/comments.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;

$this->title = Html::encode($user['username']).'的全部回复';
$settings = Yii::$app->params['settings'];

?>

<div class="row">
<div class="col-md-8 sf-left">

<div class="box">
	<div class="cell">
		<?= Html::a('首页', ['topic/index']), '&nbsp;›&nbsp;', 
			Html::a(Html::encode($user['username']), ['user/view', 'username'=>$user['username']]), 
			'&nbsp;›&nbsp;全部回帖' ?>
	</div>
<?php
foreach($comments as $comment):
?>
	<div class="cell gray small bg-info">
		<p class='fr'><?= Yii::$app->getFormatter()->asRelativeTime($comment['created_at']) ?></p>
		回复了 <?=Html::encode($comment['topic']['author']['username']) ?> 创建的主题 › <?=Html::a(Html::encode($comment['topic']['title']), ['topic/view', 'id'=>$comment['topic_id']]) ?>
	</div>
	<div class="cell">
		<?= Html::encode($comment['content']) ?>
	</div>
<?php endforeach; ?>
	<div class="item-pagination">
	<?php
	echo LinkPager::widget([
	    'pagination' => $pages,
		'maxButtonCount'=>5,
	]);
	?>
	</div>
</div>

</div>

<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>

</div>

views/user/notifications.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\Notice;
use app\models\Topic;

$this->title = '提醒系统';
?>

<div class="row">
<div class="col-md-8 sf-left">

<div class="box">
<div class="inner">
	<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
</div>
<?php
foreach($notices as $notice) {
	echo '<div class="cell item clearfix">
			<div class="item-avatar-small">',
				Html::a(Html::img('@web/'.str_replace('{size}', 'small', $notice['source']['avatar']), ["alt" => Html::encode($notice['source']['username'])]), ['user/view', 'username'=>Html::encode($notice['source']['username'])]),
			'</div>
		 	 <div class="item-notice">',
				Html::a(Html::encode($notice['source']['username']), ['user/view', 'username'=>Html::encode($notice['source']['username'])]), ' ';
				if($notice['type'] == Notice::TYPE_COMMENT) {
					echo '回复了您的帖子【'. Html::a(Html::encode($notice['topic']['title']), Topic::getRedirectUrl($notice['topic_id'], $notice['position'])) . '】',
						$notice['notice_count']>0?'<span class="small gray">(省略类似通知'.$notice['notice_count'].'次)</span>':'';
				} else if($notice['type'] == Notice::TYPE_MENTION) {
					if ($notice['position'] > 0) {
						echo '在主题【'. Html::a(Html::encode($notice['topic']['title']), Topic::getRedirectUrl($notice['topic_id'], $notice['position'])) . '】的回帖中提到了您';
					} else {
						echo '在主题【'. Html::a(Html::encode($notice['topic']['title']), ['topic/view', 'id'=>$notice['topic_id']]) . '】中提到了您';
					}
				} else if($notice['type'] == Notice::TYPE_FOLLOW_TOPIC) {
						echo '收藏了您发布的主题【', Html::a(Html::encode($notice['topic']['title']), ['topic/view', 'id'=>$notice['topic_id']]), '】';
				} else if($notice['type'] == Notice::TYPE_FOLLOW_USER) {
						echo '关注了您';
				}
		echo '</div>';
	echo '</div>';
}
?>
<div class="item-pagination">
<?php
echo LinkPager::widget([
    'pagination' => $pages,
]);
?>
</div>

</div>
</div>

<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>

</div>

views/user/setting.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;
use app\models\UserInfo;
use app\models\UploadForm;
use app\models\ChangePasswordForm;
use app\models\ChangeEmailForm;

$this->title = '会员设置';
$session = Yii::$app->getSession();
$me = Yii::$app->getUser()->getIdentity();
$cpModel = new ChangePasswordForm();
$ceModel = new ChangeEmailForm();

?>

<div class="row">
<div class="col-md-8 sf-left">

<div class="box">
	<div class="inner">
		<?= Html::a('首页', ['topic/index']), '&nbsp;›&nbsp;', $this->title ?>
	</div>
<?php if ($me->isWatingActivation()) : ?>
	<div class="cell bg-info" id="activate"><strong>会员激活</strong></div>
	<div class="cell">
<?php
if ( $session->hasFlash('activateMailNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('activateMailNG'),
		]);
} else if ( $session->hasFlash('activateMailOK') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-success'],
		   'body' => $session->getFlash('activateMailOK'),
		]);
}
?>
		您还有没有激活，请进您注册时填写的邮箱(<?= $me->email ?>)，点击激活链接。<br />
		<?= Html::a('重发激活邮件', ['user/send-activate-mail']) ?> | <a href="#password">修改邮箱</a>
	</div>
<?php endif; ?>
	<div class="cell bg-info" id="info"><strong>修改信息</strong></div>
	<div class="cell cell-form">
<?php
if ( $session->hasFlash('EditProfileNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('EditProfileNG'),
		]);
} else if ( $session->hasFlash('EditProfileOK') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-success'],
		   'body' => $session->getFlash('EditProfileOK'),
		]);
}
?>
<?php $form = ActiveForm::begin([
		'action' => ['user/edit-profile'],
		'layout' => 'horizontal',
		]); ?>
		<div class="form-group">
			<label class="control-label col-sm-3 username-label">用户名</label>
			<div class="col-sm-6" style="padding-top:7px;">
				<strong><?= $me->username ?></strong>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-3 status-label">状态</label>
			<div class="col-sm-6" style="padding-top:7px;">
				<?= $me->getStatus() ?>
			</div>
		</div>
		<?= $form->field($me->userInfo, 'website')->textInput(['maxlength'=>100]) ?>
		<?= $form->field($me->userInfo, 'about')->textArea(['maxlength'=>255]) ?>
        <div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('修改', ['class' => 'btn btn-primary']) ?>
			</div>
        </div>
<?php ActiveForm::end(); ?>
	</div>
	<div class="cell bg-info" id="avatar"><strong>修改头像</strong></div>
	<div class="cell cell-form">
<?php
if ( $session->hasFlash('setAvatarNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('setAvatarNG'),
		]);
} else if ( $session->hasFlash('setAvatarOK') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-success'],
		   'body' => $session->getFlash('setAvatarOK'),
		]);
}
?>
<?php $form = ActiveForm::begin([
		'action' => ['user/avatar'],
		'options' => ['enctype' => 'multipart/form-data'],
		'layout' => 'horizontal',
		]); ?>
		<div class="form-group">
			<label class="control-label col-sm-3 avatar-label">当前头像</label>
			<div class="col-sm-6">
			<?= Html::img('@web/'.str_replace('{size}', 'large', $me->avatar)), ' ', Html::img('@web/'.str_replace('{size}', 'normal', $me->avatar)), ' ', Html::img('@web/'.str_replace('{size}', 'small', $me->avatar)) ?>
			</div>
		</div>
		<?= $form->field((new UploadForm()), 'file')->fileInput() ?>

        <div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('上传', ['class' => 'btn btn-primary']) ?>
			</div>
        </div>
<?php ActiveForm::end(); ?>
	</div>
	<div class="cell bg-info" id="email"><strong>修改邮箱</strong></div>
	<div class="cell cell-form">
<?php
if ( $session->hasFlash('chgEmailNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('chgEmailNG'),
		]);
} else if ( $session->hasFlash('chgEmailOK') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-success'],
		   'body' => $session->getFlash('chgEmailOK'),
		]);
}
?>
<?php $form = ActiveForm::begin([
		'action' => ['user/change-email'],
		'layout' => 'horizontal',
		]);
?>
		<div class="form-group">
			<label class="control-label col-sm-3 username-label">当前邮箱</label>
			<div class="col-sm-6" style="padding-top:7px;">
				<strong><?= $me->email ?></strong>
			</div>
		</div>
		<?= $form->field($ceModel, 'email')->textInput(['maxlength'=>50]) ?>
		<?= $form->field($ceModel, 'password')->passwordInput(['maxlength'=>20]) ?>
        <div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('修改', ['class' => 'btn btn-primary']) ?>
			</div>
        </div>
<?php ActiveForm::end(); ?>
	</div>
	<div class="cell bg-info" id="password"><strong>修改密码</strong></div>
	<div class="cell cell-form">
<?php
if ( $session->hasFlash('chgPwdNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('chgPwdNG'),
		]);
} else if ( $session->hasFlash('chgPwdOK') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-success'],
		   'body' => $session->getFlash('chgPwdOK'),
		]);
}
?>
<?php $form = ActiveForm::begin([
		'action' => ['user/change-password'],
		'layout' => 'horizontal',
		]);
?>
		<?= $form->field($cpModel, 'old_password')->passwordInput(['maxlength'=>20]) ?>
		<?= $form->field($cpModel, 'password')->passwordInput(['maxlength'=>20]) ?>
		<?= $form->field($cpModel, 'password_repeat')->passwordInput(['maxlength'=>20]) ?>
        <div class="form-group">
			<div class="col-sm-offset-3 col-sm-9">
            <?= Html::submitButton('修改', ['class' => 'btn btn-primary']) ?>
			</div>
        </div>
<?php ActiveForm::end(); ?>
	</div>
</div>

</div>

<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>

</div>