controllers/SiteController.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

namespace app\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\ForgotPasswordForm;
use app\models\ResetPasswordForm;
use app\models\SignupForm;
use app\models\ContactForm;
use app\models\Auth;
use app\models\User;
use app\models\Token;

/**
 * Site controller
 */
class SiteController extends AppController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'forgot-password', 'reset-password'],
                'rules' => [
                    [
                        'actions' => ['signup', 'forgot-password', 'reset-password'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			    'height' => 40,
				'maxLength' => 5,
				'minLength' => 4,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function onAuthSuccess($client)
    {
		$sourceName = [
			'qq'=>'qq',
			'weibo'=>'微博',
			'weixin'=>'微信',
			'baidu'=>'百度',
		];
		$me = Yii::$app->getUser();

		$source = $client->getId();
		$attr = $client->getUserAttributes();

        $auth = Auth::findOne([
            'source' => $source,
            'source_id' => (string)$attr['id'],
        ]);

        if ($me->getIsGuest()) {
            if ($auth) { // login
                $user = $auth->user;
                $me->login($user);
            } else { // signup
				$attr['source'] = $source;
//				$attr['sourceName'] = $client->defaultName();
				$attr['sourceName'] = $sourceName[$source];
				$session = Yii::$app->getSession();
				$session->set('authInfo', $attr);
				return $this->redirect(['auth-bind-account']);

            }
        } else { // user already logged in
            if (!$auth) { // add auth provider
                $auth = new Auth([
                    'user_id' => Yii::$app->getUser()->id,
                    'source' => $source,
                    'source_id' => (string)$attr['id'],
                ]);
                $auth->save();
            }
        }
    }

    public function actionAuthSignup()
    {
		$session = Yii::$app->getSession();
		if( !$session->has('authInfo') ) {
			return $this->redirect(['login']);
		}
		$attr = $session->get('authInfo');

        $model = new SignupForm(['action' => SignupForm::ACTION_AUTH_SIGNUP]);
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($user = $model->signup()) {
                $auth = new Auth([
                    'user_id' => $user->id,
                    'source' => (string)$attr['source'],
                    'source_id' => (string)$attr['id'],
                ]);
                if ($auth->save()) {
					$session->remove('authInfo');
                } else {
                    throw new ServerErrorHttpException(implode('<br />', $auth->getFirstErrors()));
                }
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

		return $this->render('signup', [
            'model' => $model,
            'authInfo' => $attr,
        ]);
    }

    public function actionAuthBindAccount()
    {
        if (! Yii::$app->getUser()->getIsGuest()) {
            return $this->goHome();
        }

		$session = Yii::$app->getSession();
		if( !$session->has('authInfo') ) {
			return $this->redirect(['login']);
		}
		$attr = $session->get('authInfo');

        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            $auth = new Auth([
                'user_id' => Yii::$app->getUser()->id,
                'source' => (string)$attr['source'],
                'source_id' => (string)$attr['id'],
            ]);
            if ($auth->save()) {
				$session->remove('authInfo');
            } else {
                throw new ServerErrorHttpException(implode('<br />', $auth->getFirstErrors()));
            }
            return $this->goHome();
        } else {
			return $this->render('authBindAccount', [
	            'model' => $model,
	            'authInfo' => $attr,
	        ]);
        }

    }

    public function actionLogin()
    {
        if (! Yii::$app->getUser()->getIsGuest()) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionOffline()
    {
        return $this->render('offline');
    }

    public function actionLogout()
    {
        Yii::$app->getUser()->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
		if ( intval($this->settings['close_register']) === 1) {
            return $this->render('opResult', ['title'=>'用户注册已关闭', 'status'=>'success', 'msg'=>'请使用'. \yii\helpers\Html::a('第三方帐号登录', ['site/login'])]);
		}
        $model = new SignupForm();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
					if ($user->status == User::STATUS_INACTIVE) {
				        return $this->render('opResult', ['title'=>'帐号注册成功', 'status'=>'success', 'msg'=>'感谢您的注册，激活邮件已发送到您的注册邮箱。请去点击激活。']);
					} else if ($user->status == User::STATUS_ADMIN_VERIFY) {
				        return $this->render('opResult', ['title'=>'帐号注册成功', 'status'=>'success', 'msg'=>'感谢您的注册，请等待管理员确认。']);
					} else {
                    	return $this->goHome();
					}
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionForgotPassword()
    {
        try {
       		$model = new ForgotPasswordForm();
        } catch (InvalidParamException $e) {
	        return $this->render('opResult', ['title'=>'密码重置申请', 'status'=>'warning', 'msg'=>$e->getMessage()]);
		}
        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate()) {
        	try {
				$model->apply();
				return $this->render('opResult', ['title'=>'密码重置申请', 'status'=>'success', 'msg'=>'密码重置链接已发送到您的邮箱，请进邮箱确认。']);
        	} catch (InvalidParamException $e) {
                Yii::$app->getSession()->setFlash('sendPwdNG', $e->getMessage());
			}
        }

        return $this->render('forgotPassword', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
	        return $this->render('opResult', ['title'=>'密码重置失败', 'status'=>'warning', 'msg'=>$e->getMessage()]);
        }

        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate() && $model->resetPassword()) {
            return $this->render('opResult', ['title'=>'密码重置成功', 'status'=>'success', 'msg'=>'新密码已生效']);
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionVerifyEmail($token)
    {
        try {
            $token = Token::findByToken($token, Token::TYPE_EMAIL);
        } catch (InvalidParamException $e) {
        	return $this->render('opResult', ['title'=>'邮箱绑定失败', 'status'=>'warning', 'msg'=>$e->getMessage()]);
        }

		$token->status = Token::STATUS_USED;
		$token->save(false);

		$model = new \app\models\ChangeEmailForm(['email'=>$token->ext]);
		if ( !$model->validate() ) {
        	return $this->render('opResult', ['title'=>'邮箱绑定失败', 'status'=>'warning', 'msg'=>'申请绑定邮箱['.$token->ext.']已被注册使用']);
		}

		$user = $token->user;
		$user->email = $token->ext;
		$user->save(false);

        return $this->render('opResult', ['title'=>'邮箱绑定成功', 'status'=>'success', 'msg'=>'新邮件绑定成功']);
    }

    public function actionActivate($token)
    {
        try {
            $token = Token::findByToken($token, Token::TYPE_REG);
        } catch (InvalidParamException $e) {
        	return $this->render('opResult', ['title'=>'帐号激活失败', 'status'=>'warning', 'msg'=>$e->getMessage()]);
        }

		$user = $token->user;

		$token->status = Token::STATUS_USED;
		$token->save(false);

		if ( !empty($token->ext) && $user->email !== $token->ext && User::findOne(['email'=>$token->ext]) ) {
        	return $this->render('opResult', ['title'=>'帐号激活失败', 'status'=>'warning', 'msg'=>'申请绑定邮箱['.$token->ext.']已被注册使用']);
		}
		if (intval($this->settings['admin_verify']) === 1) {
			$user->status = User::STATUS_ADMIN_VERIFY;
			$result = ['title'=>'注册邮箱确认成功', 'status'=>'success', 'msg'=>'注册邮箱确认成功，请等待管理员验证。'];
		} else {

views/site/authBindAccount.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use Yii;

$this->title = '绑定本站帐号';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell">
            <?php $form = ActiveForm::begin([
			    'layout' => 'horizontal',
				'id' => 'form-auth-bind-account'
			]); ?>
			<div class="form-group">
				<div class="col-sm-offset-3 col-sm-6" style="padding-top:7px;">
					您已通过<?= $authInfo['sourceName'] ?>登录
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3">用户名</label>
				<div class="col-sm-6" style="padding-top:7px;">
					<strong><?= $authInfo['username'] ?></strong>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3">还没本站帐号</label>
				<div class="col-sm-6">
					<?= Html::a('创建本站帐号并绑定', ['auth-signup'], ['class'=>'btn btn-primary']) ?>
				</div>
			</div>
			<br /><strong>绑定本站账号</strong><hr>
            <?= $form->field($model, 'username')->textInput(['maxlength'=>20]) ?>
            <?= $form->field($model, 'password')->passwordInput(['maxlength'=>20]) ?>
            <div class="form-group">
				<div class="col-sm-offset-3 col-sm-9">
                <?= Html::submitButton('绑定', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
				&nbsp;&nbsp;<?= Html::a('忘记密码了', ['site/forgot-password']) ?>
				</div>
            </div>
            <?php ActiveForm::end(); ?>
		</div>
	</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/error.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\Alert;

$session = Yii::$app->getSession();

$this->title = '出错了';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell">
    <p><strong><?= Html::encode($name) ?></strong></p>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        论坛处理您的请求时，发生了以上错误。
    </p>
    <p>
        如您认为是服务器错误或论坛程序错误，请联系站长 <?= Yii::$app->params['setting']['admin_email'] ?>
    </p>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/forgotPassword.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Alert;

$session = Yii::$app->getSession();

$this->title = '通过电子邮件重设密码';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
<?php
if ( $session->hasFlash('sendPwdNG') ) {
	echo Alert::widget([
		   'options' => ['class' => 'alert-warning'],
		   'body' => $session->getFlash('sendPwdNG'),
		]);
}
?>
            <?php $form = ActiveForm::begin([
			    'layout' => 'horizontal',
				'id' => 'form-fogot-password'
			]); ?>
                <?= $form->field($model, 'email')->textInput(['maxlength'=>50]) ?>
                <div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
                    <?= Html::submitButton('继续', ['class' => 'btn btn-primary']) ?>
					</div>
                </div>
            <?php ActiveForm::end(); ?>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '登录';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
            <?php $form = ActiveForm::begin([
			    'layout' => 'horizontal',
				'id' => 'form-login'
			]); ?>
            <?= $form->field($model, 'username')->textInput(['maxlength'=>20]) ?>
            <?= $form->field($model, 'password')->passwordInput(['maxlength'=>20]) ?>
			<?= $form->field($model, 'rememberMe')->checkbox() ?>
<?php
	if ( intval(Yii::$app->params['settings']['captcha_enabled']) === 1 ) {
		echo $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::classname());
	}
?>
            <div class="form-group">
				<div class="col-sm-offset-3 col-sm-9">
                <?= Html::submitButton('登录', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
				&nbsp;&nbsp;<?= Html::a('忘记密码了', ['site/forgot-password']) ?>
				</div>
            </div>
            <?php ActiveForm::end(); ?>
<?php if ( intval(Yii::$app->params['settings']['auth_enabled']) === 1 ) : ?>
			<h6 class="login-three-home"><strong>第三方账号直接登录</strong></h6>
			<?=
			\yii\authclient\widgets\AuthChoice::widget([
			    'baseAuthUrl' => ['site/auth'],
			    'popupMode' => false,
			])
			?>
<?php endif; ?>
		</div>
	</div>

</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/offline.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\Alert;

$this->title = '论坛暂时关闭';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
<?= Alert::widget([
	   'options' => ['class' => 'alert-danger'],
	   'closeButton'=>false,
	   'body' => Yii::$app->params['settings']['offline_msg'],
	]);
?>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/opResult.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\Alert;

$this->title = empty($title)?'操作结果':$title;
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
<?= Alert::widget([
	   'options' => ['class' => 'alert-'.$status],
	   'closeButton'=>false,
	   'body' => $msg,
	]);
?>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/resetPassword.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = '重设密码';
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
            <?php $form = ActiveForm::begin([
			    'layout' => 'horizontal',
				'id' => 'form-reset-password'
			]); ?>
                <?= $form->field($model, 'password')->passwordInput(['maxlength'=>20]) ?>
                <?= $form->field($model, 'password_repeat')->passwordInput(['maxlength'=>20]) ?>
                <div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
                    <?= Html::submitButton('确定', ['class' => 'btn btn-primary']) ?>
					</div>
                </div>
            <?php ActiveForm::end(); ?>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>

views/site/signup.php
<?php
/**
 * @link http://www.simpleforum.org/
 * @copyright Copyright (c) 2015 Simple Forum
 * @author Jiandong Yu admin@simpleforum.org
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\SignupForm;

if ($model->action === SignupForm::ACTION_AUTH_SIGNUP) {
	$this->title = '创建帐号并绑定第三方帐号';
	$btnLabel = '创建帐号并绑定';
} else {
	$this->title = '注册';
	$btnLabel = '注册';
}
?>

<div class="row">
<!-- sf-left start -->
<div class="col-md-8 sf-left">
	<div class="box">
		<div class="inner">
			<?= Html::a('首页', ['topic/index']), '&nbsp;/&nbsp;', $this->title ?>
		</div>
		<div class="cell cell-form">
            <?php $form = ActiveForm::begin([
			    'layout' => 'horizontal',
				'id' => 'form-signup'
			]); ?>
<?php if ($model->action === SignupForm::ACTION_AUTH_SIGNUP) : ?>
			<div class="form-group">
				<div class="col-sm-offset-3 col-sm-6" style="padding-top:7px;">
					您已通过<?= $authInfo['sourceName'] ?>登录
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3">用户名</label>
				<div class="col-sm-6" style="padding-top:7px;">
					<strong><?= $authInfo['username'] ?></strong>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-3">已有本站帐号</label>
				<div class="col-sm-6">
					<?= Html::a('绑定已有帐号', ['auth-bind-account'], ['class'=>'btn btn-primary']) ?>
				</div>
			</div>
			<br /><strong>创建本站账号</strong><hr>
<?php endif; ?>
                <?= $form->field($model, 'username')->textInput(['maxlength'=>20]) ?>
                <?= $form->field($model, 'email')->textInput(['maxlength'=>50]) ?>
                <?= $form->field($model, 'password')->passwordInput(['maxlength'=>20]) ?>
                <?= $form->field($model, 'password_repeat')->passwordInput(['maxlength'=>20]) ?>
<?php
	if ( $model->action !== SignupForm::ACTION_AUTH_SIGNUP && intval(Yii::$app->params['settings']['captcha_enabled']) === 1 ) {
		echo $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::classname());
	}
?>
                <div class="form-group">
					<div class="col-sm-offset-3 col-sm-9">
                    <?= Html::submitButton($btnLabel, ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
					</div>
                </div>
            <?php ActiveForm::end(); ?>
		</div>
	</div>
</div>
<!-- sf-left end -->

<!-- sf-right start -->
<div class="col-md-4 sf-right">
<?= $this->render('@app/views/common/_right') ?>
</div>
<!-- sf-right end -->

</div>